title: Lorenzo Fern√°ndez
logo: /assets/img/create-from-blank-instagram1080.png
description: Bienvenido a mi portafolio de proyectos de Data Analysis
show_downloads: false
theme: jekyll-theme-minimal
